import pandas as pd
import matplotlib.pyplot as plt

# Load your predictions and experimental values
data = pd.read_csv('/Users/xinawang/chemprop/CYP2D6_preds.csv')  # CSV file generated by chemprop_predict

# Assuming the CSV has columns 'true' for experimental and 'pred' for predicted values
true_values = data['CYP2D6_inhibition']
predicted_values = data['pred_0']

# Create the parity plot
plt.figure(figsize=(6, 6))
plt.scatter(true_values, predicted_values, color='blue', label='Predictions')
plt.plot([min(true_values), max(true_values)], [min(true_values), max(true_values)], color='red', linestyle='--', label='Perfect fit')
plt.xlabel('Experimental IC50')
plt.ylabel('Predicted IC50')
plt.title('Parity Plot: Experimental vs. Predicted IC50')
plt.legend()
plt.show()
